dofile("setupTests.lua")

describe("Fabrikao (startup)", function()
    local ns

    before_each(function()
        WowMock.Reset()
        ns = LoadAddon()
    end)

    it("loads every TOC file", function()
        assert.is_not_nil(ns.L)
        assert.are.equal("function", type(ns.InitSettings))
        assert.are.equal("function", type(ns.Print))
    end)

    it("on entering, sets up the saved variables and announces in chat", function()
        StartAddon(ns)
        assert.is_not_nil(FabrikaoDB)
        assert.is_not_nil(FabrikaoCharDB)
        assert.matches("initializing", WowMock.printed[1])
        assert.matches("initialization complete", WowMock.printed[2])
    end)

    it("with messages turned off, writes nothing to chat", function()
        StartAddon(ns, nil, { quiet = true })
        assert.are.equal(0, #WowMock.printed)
    end)

    it("ignores other addons' ADDON_LOADED", function()
        _G.FabrikaoDB, _G.FabrikaoCharDB = nil, nil
        FireEvent("ADDON_LOADED", "SomethingElse")
        assert.is_nil(FabrikaoDB)
        assert.are.equal(0, #WowMock.printed)
    end)

    it("registers /fabrikao and /fab", function()
        assert.are.equal("/fabrikao", SLASH_FABRIKAO1)
        assert.are.equal("/fab", SLASH_FABRIKAO2)
        assert.are.equal("function", type(SlashCmdList.FABRIKAO))
    end)
    it("/fabrikao alone opens and closes the window", function()
        StartAddon(ns)
        SlashCmdList.FABRIKAO("")
        assert.is_true(_G.FabrikaoFrame:IsShown())
        SlashCmdList.FABRIKAO("toggle")
        assert.is_false(_G.FabrikaoFrame:IsShown())
    end)

    it("has a key binding to open the window", function()
        assert.is_not_nil(BINDING_NAME_FABRIKAO_TOGGLE)
        StartAddon(ns)
        Fabrikao_Toggle()
        assert.is_true(_G.FabrikaoFrame:IsShown())
    end)

    it("creates the minimap button, and /fabrikao minimap hides it", function()
        StartAddon(ns)
        assert.is_not_nil(_G.FabrikaoMinimapButton)
        SlashCmdList.FABRIKAO("minimap")
        assert.is_true(ns.char.minimap.hide)
    end)

    it("/fabrikao version prints the TOC version, anything else the usage", function()
        SlashCmdList.FABRIKAO("version")
        assert.matches("v0%.0%.0%-test", WowMock.printed[1])
        SlashCmdList.FABRIKAO("nonsense")
        assert.matches("Usage", WowMock.printed[2])
    end)
end)
